### PR TITLE
Move Java baseline to 17

### PR DESCRIPTION
**Pull request by michalvavrik**
TSIA

### CODE REVIEW

**Comment by gtroitsk** [comment]
There is a problem using Java 17 with old dependencies grep4j and lombok. I will look at it

**Comment by michalvavrik** [comment]
> There is a problem using Java 17 with old dependencies grep4j and lombok. I will look at it

okay, maybe you can create PR as I don't really want to test this manually. Can you bump these old dependencies?

**Comment by michalvavrik** [comment]
will leave it to @gtroitsk

**Comment by michalvavrik** [comment]
Changed my mind again, I am not able to remove this dependency without considerable effort, so closing and staying on JDK 11.

**Pull request closed without merging**
